language: python

branches:
  only:
  - master
  - v0.2.0-dev

matrix:
  include:

    - python: '2.6'
      env: TOX_ENV=py26

    - python: '2.7'
      env: TOX_ENV=py27

    - python: '3.3'
      env: TOX_ENV=py33

    - python: '3.4'
      env: TOX_ENV=py34

    - python: '3.5'
      env: TOX_ENV=py35

    - python: 'pypy'
      env: TOX_ENV=pypy

    - python: '2.7'
      env: TOX_ENV=docs

    - python: '2.7'
      env: TOX_ENV=flake8

    - python: '2.7'
      env: TOX_ENV=manifest

before_install:
- pip install codecov
install:
- pip install tox
script:
- tox --hashseed 0 -e $TOX_ENV
after_success:
- codecov
notifications:
  email: false
  irc: "chat.freenode.net#ramlfications"
  slack:
    secure: TWn+jseoa8McZptuY7Zr/2AkrWKd9tSmvCoCszYkGHyHp+PAdnxH96Wxweq4pL1A1QoMtsgYM5dhPEPUfV9xCRN1FU6OMPtchMjgC740vqNsLE0+cjz6We3COw9+BHoLk7Nh2SgAzjxS9X+0Bv6tDBf1CvA7SIyM1ssLQifnX+M=
deploy:
  provider: pypi
  user: roguelynn
  password:
    secure: XgUz7PiCHCOVM1yZeNfuy2j73aAGpW5HtTocmjlKNqG9wKXGkqV4IFWneznE1n8hqQj+Tqmm4MQ0AftJcomEh9WESVsglwMOqwMericRcsVkrEq+XHPynMfqsUc/MEr+zAB/Tj9SsbYMjP8zsk4TdJx/s+EbYFXsDfHrxcQY6q4=
  on:
    tags: true
  distributions: sdist bdist_wheel
